//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::banned_words::Entity as BannedWords;
pub use super::channel_users::Entity as ChannelUsers;
pub use super::channels::Entity as Channels;
pub use super::urls::Entity as Urls;
pub use super::users::Entity as Users;
